<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $electronics = Category::where('slug', 'elektronik')->first()?->id ?? 1;
        $hp = Category::where('slug', 'handphone-tablet')->first()?->id ?? 2;
        $fashionPria = Category::where('slug', 'fashion-pria')->first()?->id ?? 3;
        $fashionWanita = Category::where('slug', 'fashion-wanita')->first()?->id ?? 4;
        $laptop = Category::where('slug', 'komputer-laptop')->first()?->id ?? 5;
        $otomotif = Category::where('slug', 'otomotif')->first()?->id ?? 6;
        $rumah = Category::where('slug', 'rumah-tangga')->first()?->id ?? 7;
        $food = Category::where('slug', 'makanan-minuman')->first()?->id ?? 8;

        $products = [
            // Handphone & Tablet
            [
                'category_id' => $hp,
                'name' => 'Apple iPhone 15 Pro Max 256GB Natural Titanium Garansi Resmi iBox',
                'slug' => 'apple-iphone-15-pro-max-256gb',
                'price' => 20999000,
                'original_price' => 24999000,
                'discount_percent' => 16,
                'stock' => 25,
                'rating' => 4.9,
                'sold_count' => 1850,
                'store_name' => 'Apple Authorised Reseller',
                'store_location' => 'Jakarta Selatan',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => true,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80',
                'description' => 'iPhone 15 Pro Max. Dirancang dengan titanium dan dilengkapi chip A17 Pro terobosan, tombol Tindakan yang dapat disesuaikan, dan sistem kamera iPhone paling andal yang pernah ada.',
            ],
            [
                'category_id' => $hp,
                'name' => 'Samsung Galaxy S24 Ultra 5G 12GB/512GB Titanium Gray Official',
                'slug' => 'samsung-galaxy-s24-ultra-5g',
                'price' => 19499000,
                'original_price' => 21999000,
                'discount_percent' => 11,
                'stock' => 18,
                'rating' => 4.9,
                'sold_count' => 1240,
                'store_name' => 'Samsung Official Store',
                'store_location' => 'Jakarta Barat',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => true,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80',
                'description' => 'Welcome to the era of mobile AI. Galaxy S24 Ultra hadir dengan Galaxy AI terintegrasi, S Pen presisi tinggi, dan layar Dynamic AMOLED 2X 120Hz terjelas.',
            ],
            [
                'category_id' => $hp,
                'name' => 'Xiaomi 14 Ultra 16GB/512GB Leica Camera Black Garansi Resmi',
                'slug' => 'xiaomi-14-ultra-16gb-512gb',
                'price' => 14999000,
                'original_price' => 16999000,
                'discount_percent' => 12,
                'stock' => 30,
                'rating' => 4.8,
                'sold_count' => 890,
                'store_name' => 'Xiaomi Official Store',
                'store_location' => 'Jakarta Pusat',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => false,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80',
                'description' => 'Fotografi tingkat profesional dengan lensa optik Leica Summilux quad camera dan chipset Snapdragon 8 Gen 3 tercepat.',
            ],

            // Komputer & Laptop
            [
                'category_id' => $laptop,
                'name' => 'MacBook Pro 16 Inch M3 Max 36GB 1TB Space Black Official',
                'slug' => 'macbook-pro-16-m3-max-36gb',
                'price' => 42999000,
                'original_price' => 46999000,
                'discount_percent' => 8,
                'stock' => 10,
                'rating' => 5.0,
                'sold_count' => 430,
                'store_name' => 'iBox Official Store',
                'store_location' => 'Jakarta Selatan',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => true,
                'is_flash_sale' => false,
                'image_url' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80',
                'description' => 'MacBook Pro paling perkasa dengan chip M3 Max 16-core CPU dan 40-core GPU. Layar Liquid Retina XDR memukau untuk workflow kreatif profesional.',
            ],
            [
                'category_id' => $laptop,
                'name' => 'ASUS ROG Zephyrus G16 RTX 4080 OLED Gaming Laptop Eclipse Gray',
                'slug' => 'asus-rog-zephyrus-g16-rtx-4080',
                'price' => 35999000,
                'original_price' => 39999000,
                'discount_percent' => 10,
                'stock' => 14,
                'rating' => 4.9,
                'sold_count' => 670,
                'store_name' => 'ASUS Official Store',
                'store_location' => 'Bandung',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => true,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=80',
                'description' => 'Laptop gaming ultra-tipis dengan chassis CNC aluminium, layar ROG Nebula OLED 240Hz, Intel Core Ultra 9 dan NVIDIA GeForce RTX 4080.',
            ],
            [
                'category_id' => $laptop,
                'name' => 'Logitech MX Master 3S Wireless Performance Mouse Graphic Black',
                'slug' => 'logitech-mx-master-3s-wireless-mouse',
                'price' => 1549000,
                'original_price' => 1899000,
                'discount_percent' => 18,
                'stock' => 85,
                'rating' => 4.9,
                'sold_count' => 5400,
                'store_name' => 'Logitech Official Store',
                'store_location' => 'Jakarta Barat',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => false,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80',
                'description' => 'Mouse presisi legendaris dengan klik senyap 90%, sensor 8000 DPI Darkfield pada permukaan kaca, dan scrolling MagSpeed ultra-cepat.',
            ],

            // Elektronik
            [
                'category_id' => $electronics,
                'name' => 'Sony WH-1000XM5 Wireless Noise Canceling Headphones Silver',
                'slug' => 'sony-wh-1000xm5-wireless-headphones',
                'price' => 4899000,
                'original_price' => 5999000,
                'discount_percent' => 18,
                'stock' => 40,
                'rating' => 4.9,
                'sold_count' => 3100,
                'store_name' => 'Sony Audio Official',
                'store_location' => 'Jakarta Selatan',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => true,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
                'description' => 'Standar emas peredam bising aktif (ANC) dengan Auto NC Optimizer, mikrofon kualitas panggilan jernih kristal, dan daya tahan baterai hingga 30 jam.',
            ],
            [
                'category_id' => $electronics,
                'name' => 'LG C3 55 Inch OLED EVO 4K Smart TV 120Hz G-Sync Gaming',
                'slug' => 'lg-c3-55-inch-oled-evo-4k-smart-tv',
                'price' => 17499000,
                'original_price' => 20999000,
                'discount_percent' => 16,
                'stock' => 12,
                'rating' => 4.9,
                'sold_count' => 290,
                'store_name' => 'LG Electronics Official',
                'store_location' => 'Tangerang',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => false,
                'is_flash_sale' => false,
                'image_url' => 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80',
                'description' => 'Nikmati warna hitam sempurna dan kontras tak terhingga dengan prosesor α9 AI 4K Gen6, webOS Smart Platform, dan 4 port HDMI 2.1.',
            ],

            // Fashion Pria
            [
                'category_id' => $fashionPria,
                'name' => 'Sepatu Sneakers Nike Air Jordan 1 Retro High OG Chicago Lost & Found',
                'slug' => 'nike-air-jordan-1-retro-high-og-chicago',
                'price' => 3899000,
                'original_price' => 4500000,
                'discount_percent' => 13,
                'stock' => 15,
                'rating' => 4.9,
                'sold_count' => 1120,
                'store_name' => 'Kick Avenue Official',
                'store_location' => 'Jakarta Barat',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => true,
                'is_flash_sale' => false,
                'image_url' => 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&q=80',
                'description' => 'Ikon street style abadi Air Jordan 1 Chicago versi Lost & Found dengan material kulit premium dan detail patina vintage kolektor.',
            ],
            [
                'category_id' => $fashionPria,
                'name' => 'Jaket EIGER Outdoorgear Windproof Waterproof Warm Jacket Navy',
                'slug' => 'jaket-eiger-outdoorgear-windproof',
                'price' => 699000,
                'original_price' => 899000,
                'discount_percent' => 22,
                'stock' => 60,
                'rating' => 4.8,
                'sold_count' => 4200,
                'store_name' => 'EIGER Adventure Store',
                'store_location' => 'Bandung',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => false,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&q=80',
                'description' => 'Jaket outdoor serbaguna tahan angin dan air hujan ringan. Cocok untuk petualangan naik gunung maupun kendaraan bermotor sehari-hari.',
            ],

            // Fashion Wanita
            [
                'category_id' => $fashionWanita,
                'name' => 'Tas Tangan Wanita Premium Leather Handbag Crossbody Bag Beige',
                'slug' => 'tas-tangan-wanita-premium-leather-handbag',
                'price' => 450000,
                'original_price' => 750000,
                'discount_percent' => 40,
                'stock' => 45,
                'rating' => 4.9,
                'sold_count' => 2800,
                'store_name' => 'Charles & Keith Gallery',
                'store_location' => 'Surabaya',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => true,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80',
                'description' => 'Tas wanita elegan desain terkini dengan kompartemen luas, jahitan rapi presisi, dan tali bahu adjustable yang nyaman.',
            ],
            [
                'category_id' => $fashionWanita,
                'name' => 'Kacamata Hitam Sunglasses Vintage Oval Cateye Korean Style',
                'slug' => 'kacamata-hitam-sunglasses-vintage-korean',
                'price' => 129000,
                'original_price' => 250000,
                'discount_percent' => 48,
                'stock' => 100,
                'rating' => 4.8,
                'sold_count' => 8900,
                'store_name' => 'Bridges Eyewear Official',
                'store_location' => 'Jakarta Pusat',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => false,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80',
                'description' => 'Sunglasses UV400 Protection anti radiasi dengan frame acetate ringan nan elegan khas Korean Aesthetic.',
            ],

            // Makanan & Minuman
            [
                'category_id' => $food,
                'name' => 'Biji Kopi Arabika Gayo Single Origin Specialty Roast 500g Tokopedia NOW',
                'slug' => 'biji-kopi-arabika-gayo-single-origin-500g',
                'price' => 135000,
                'original_price' => 165000,
                'discount_percent' => 18,
                'stock' => 120,
                'rating' => 5.0,
                'sold_count' => 6400,
                'store_name' => 'Anomali Coffee Store',
                'store_location' => 'Jakarta Selatan',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => false,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&q=80',
                'description' => 'Biji kopi pilihan dari dataran tinggi Aceh Gayo. Profil sangrai medium roast dengan keasaman seimbang dan aroma floral karamel yang manis.',
            ],

            // Rumah Tangga
            [
                'category_id' => $rumah,
                'name' => 'Air Fryer Digital Low Watt 4.5L Stainless Touchscreen Smart Cooker',
                'slug' => 'air-fryer-digital-low-watt-4-5l',
                'price' => 689000,
                'original_price' => 1299000,
                'discount_percent' => 46,
                'stock' => 50,
                'rating' => 4.9,
                'sold_count' => 3700,
                'store_name' => 'Philips Home Appliances',
                'store_location' => 'Jakarta Utara',
                'is_official_store' => true,
                'is_power_merchant' => true,
                'is_featured' => true,
                'is_flash_sale' => true,
                'image_url' => 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80',
                'description' => 'Menggoreng tanpa minyak dengan sirkulasi udara 360° Rapid Air Technology. Hemat listrik hanya 650Watt dan mudah dibersihkan.',
            ],
        ];

        foreach ($products as $prod) {
            Product::updateOrCreate(['slug' => $prod['slug']], $prod);
        }
    }
}
